controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation


home:
    path: /
    methods: [ "GET" ]
    controller: App\Controller\HomeController::index

login:
    path: /login
    methods: [ "GET" ]
    controller: App\Controller\ConnexionController::index

login_process:
    path: /login/process
    methods: [ "POST" , "GET" ]
    controller: App\Controller\ConnexionController::loginProcess

logout: 
    path: /logout
    methods: [ "GET" ]
    controller: App\Controller\ConnexionController::logout



register:
    path: /register
    methods: [ "GET" ]
    controller: App\Controller\ConnexionController::registerIndex

register_process:
    path: /register/process
    methods: [ "POST" ]
    controller: App\Controller\ConnexionController::registerProcess



delete:
    path: /delete
    methods: [ "GET" ]
    controller: App\Controller\ConnexionController::delete

delete_process:
    path: /delete/process
    methods: [ "POST" , "GET" ]
    controller: App\Controller\ConnexionController::deleteProccess



# ! tempController
getHashedPassword:
    path: /get/password
    methods: ["GET"]
    controller: App\Controller\ConnexionController::generatePassword



property_list:
    path: /property
    methods: ["GET"]
    controller: App\Controller\PropertyController::list

see_property:
    path: /property/{id}
    methods: ["GET"]
    controller: App\Controller\PropertyController::modify
    requirements:
        id: '\d+'

modify_property_process:
    path: /property/modify/process
    methods: [ "POST" ]
    controller: App\Controller\PropertyController::modifyProcess

add_property:
    path: /property/add
    methods: [ "GET" ]
    controller: App\Controller\PropertyController::add

add_property_process:
    path: /property/add/process
    methods: [ "POST" ]
    controller: App\Controller\PropertyController::addProcess



representative_list:
    path: /representative
    methods: [ "GET" ]
    controller: App\Controller\RepresentativeController::list

modify_representative:
    path: /representative/modify/{id}
    methods: [ "GET" ]
    controller: App\Controller\RepresentativeController::modify
    requirements:
        id: '\d+'

modify_representative_process:
    path: /representative/modify/process
    methods: [ "POST" ]
    controller: App\Controller\RepresentativeController::modifyProcess

add_representative:
    path: /representative/add
    methods: [ "GET" ]
    controller: App\Controller\RepresentativeController::add

add_representative_process:
    path: /representative/add/process
    methods: [ "POST" ]
    controller: App\Controller\RepresentativeController::addProcess



tenant_list:
    path: /tenant
    methods: [ "GET" ]
    controller: App\Controller\TenantController::list

modify_tenant:
    path: /tenant/modify/{id}
    methods: [ "GET" ]
    controller: App\Controller\TenantController::modify
    requirements:
        id: '\d+'

modify_tenant_process:
    path: /tenant/modify/process
    methods: [ "POST" ]
    controller: App\Controller\TenantController::modifyProcess

add_tenant:
    path: /tenant/add
    methods: [ "GET" ]
    controller: App\Controller\TenantController::add

add_tenant_process:
    path: /tenant/add/process
    methods: [ "POST" ]
    controller: App\Controller\TenantController::addProcess



see_rent:
    path: /rent/see/{id}
    methods: [ "GET" ]
    controller: App\Controller\RentController::index
    requirements:
        id: '\d+'

list_rent:
    path: /rent/list
    methods: [ "GET" ]
    controller: App\Controller\RentController::list

add_rent_from_tenant: 
    path: /rent/add/tenant/{id}
    methods: [ "GET" ]
    controller: App\Controller\RentController::addFromTenant
    requirements:
        id: '\d+'


add_rent_from_property: 
    path: /rent/add/property/{id}
    methods: [ "GET" ]
    controller: App\Controller\RentController::addFromProperty
    requirements:
        id: '\d+'

add_rent_process:
    path: /rent/add/process
    methods: [ "POST" ]
    controller: App\Controller\RentController::addProcess

rent_signup_process:
    path: /rent/signup/process
    methods: [ "POST" ]
    controller: App\Controller\RentController::signupProcess