controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation


home:
    path: /
    methods: [ "GET" ]
    controller: App\Controller\HomeController::index

login:
    path: /login
    methods: [ "GET" ]
    controller: App\Controller\ConnexionController::index

login_process:
    path: /login/process
    methods: [ "POST" , "GET" ]
    controller: App\Controller\ConnexionController::loginProcess

logout: 
    path: /logout
    methods: [ "GET" ]
    controller: App\Controller\ConnexionController::logout



register:
    path: /register
    methods: [ "GET" ]
    controller: App\Controller\ConnexionController::registerIndex

register_process:
    path: /register/process
    methods: [ "POST" ]
    controller: App\Controller\ConnexionController::registerProcess



delete:
    path: /delete
    methods: [ "GET" ]
    controller: App\Controller\ConnexionController::delete

delete_process:
    path: /delete/proccess
    methods: [ "POST" , "GET" ]
    controller: App\Controller\ConnexionController::deleteProccess



# tempController
getHashedPassword:
    path: /get/password
    methods: ["GET"]
    controller: App\Controller\ConnexionController::generatePassword



property_list_owner:
    path: /property
    methods: ["GET"]
    controller: App\Controller\PropertyController::list

see_property:
    path: /property/{id}
    methods: ["GET"]
    controller: App\Controller\PropertyController::see
    requirements:
        id: '\d+'

add_property:
    path: /property/add
    methods: [ "GET" ]
    controller: App\Controller\PropertyController::add